In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
# pip install ipdb

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# !pip install --verbose --no-cache-dir torch-scatter
# !pip install --verbose --no-cache-dir torch-sparse
# !pip install --verbose --no-cache-dir torch-cluster
# !pip install torch-geometric
# !pip install tensorboardX
# !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
# !unzip ngrok-stable-linux-amd64.zip
# !pip install pgmpy

In [3]:
# !git clone https://Shray64:shray1998@github.com/Shray64/GraphXAI.git

Cloning into 'GraphXAI'...
remote: Enumerating objects: 20664, done.
remote: Counting objects: 100% (655/655), done.
remote: Compressing objects: 100% (252/252), done.
remote: Total 20664 (delta 474), reused 463 (delta 394), pack-reused 20009
Receiving objects: 100% (20664/20664), 254.33 MiB | 26.08 MiB/s, done.
Resolving deltas: 100% (18680/18680), done.
Checking out files: 100% (25204/25204), done.


In [8]:
!git clone https://github.com/YANI-ALT/FML-GNN_DisagreementProblem.git

Cloning into 'FML-GNN_DisagreementProblem'...
remote: Enumerating objects: 15679, done.
remote: Counting objects: 100% (15679/15679), done.
remote: Compressing objects: 100% (630/630), done.
remote: Total 15679 (delta 15037), reused 15637 (delta 15009), pack-reused 0
Receiving objects: 100% (15679/15679), 38.51 MiB | 18.62 MiB/s, done.
Resolving deltas: 100% (15037/15037), done.
Checking out files: 100% (25266/25266), done.


In [20]:
cd FML-GNN_DisagreementProblem/GNNModels/

[Errno 2] No such file or directory: 'FML-GNN_DisagreementProblem/GNNModels/'
/content/FML-GNN_DisagreementProblem/GNNModels


In [11]:
cd GraphXAI-main/

/content/FML-GNN_DisagreementProblem/GraphXAI-main


In [19]:
pip install -e .

ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /content/FML-GNN_DisagreementProblem/GNNModels


In [13]:
cd ../GNNModels

/content/FML-GNN_DisagreementProblem/GNNModels


In [65]:
#Notebook starts from here

In [14]:
import torch
from Models import *
from Train import *
from torch_geometric.datasets import Planetoid
from torch_geometric.transforms import NormalizeFeatures
from torch_geometric.datasets import TUDataset
import matplotlib.pyplot as plt

In [15]:
dataset = TUDataset(root='data/TUDataset', name='PROTEINS')

In [16]:
model = GCN_3L(hidden_channels=64,num_features=dataset.num_node_features,num_classes=dataset.num_classes)

params={'lr':0.01,'epochs':10,'verbose':True,'save_wts':''}
# params={'lr':0.01,'epochs':150,'verbose':True,'save_wts':'checkpoints/GCN_3L_PROTEINS_epochs=300.pt'}

TrainModel(model,dataset,params,type='GC')

{'Loss': None, 'Train': 0.7136431784107946, 'Test': 0.7017937219730942}

In [25]:
# cd GraphXAI

/content/GraphXAI


In [66]:
from graphxai.explainers import GNNExplainer, IntegratedGradExplainer, PGExplainer, CAM, PGMExplainer

In [ ]:
# def gnex_imp_nodes(data_idx):
#   node_exp = gnex.get_explanation_graph(dataset[data_idx].x, dataset[data_idx].edge_index, forward_kwargs={'batch':None})

#   imp_nodes = []

#   for k in node_exp.node_reference.keys():

#       if node_exp.node_imp[node_exp.node_reference[k]].item() == 1:

#           imp_nodes.append(k)

#   return imp_nodes



In [27]:
gnex = GNNExplainer(model)
gnex_ne = gnex.get_explanation_graph(dataset[5].x, dataset[5].edge_index, forward_kwargs={'batch':None})

In [28]:
gnex_ne.node_imp

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [29]:
gnex_ne.edge_imp

tensor([0.1340, 0.1503, 0.1467,  ..., 0.1291, 0.1431, 0.1310])

In [30]:
igex = IntegratedGradExplainer(model, criterion=torch.nn.CrossEntropyLoss())
igex_ne = igex.get_explanation_graph(dataset[5].edge_index, dataset[5].x, dataset[5].y, forward_kwargs={'batch':None})

In [31]:
igex_ne.node_imp

In [ ]:
igex_ne.edge_imp

In [54]:
pgex = PGExplainer(model, emb_layer_name = 'conv2',  max_epochs = 5, lr = 0.01, explain_graph=True)

In [55]:
pgex.train_explanation_model(dataset, forward_kwargs={'batch':None})

100%|██████████| 1113/1113 [00:17<00:00, 62.07it/s]


Epoch: 0 | Loss: 1307.0850697755814


100%|██████████| 1113/1113 [00:15<00:00, 70.69it/s]


Epoch: 1 | Loss: 1245.6341643035412


100%|██████████| 1113/1113 [00:16<00:00, 69.52it/s]


Epoch: 2 | Loss: 1155.4612934291363


100%|██████████| 1113/1113 [00:16<00:00, 69.34it/s]


Epoch: 3 | Loss: 1019.9534672498703


100%|██████████| 1113/1113 [00:15<00:00, 72.79it/s]

Epoch: 4 | Loss: 847.5050546824932


In [51]:
pgex_ne = pgex.get_explanation_graph(dataset[5].x, dataset[5].edge_index, forward_kwargs={'batch':None})

In [52]:
pgex_ne.node_imp

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 

In [53]:
pgex_ne.edge_imp

tensor([0.1170, 0.1140, 0.1121,  ..., 0.2656, 0.2404, 0.2538])

In [57]:
cam = CAM(model)

In [59]:
cam_ne = cam.get_explanation_graph(dataset[5].x, dataset[5].edge_index, forward_kwargs={'batch':None})

In [60]:
cam_ne.node_imp

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0159,
        0.0200, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0142, 0.0094, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0159, 0.0200, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0142, 0.0094, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0142,
        0.0094, 0.0000, 0.0000, 0.0000, 

In [67]:
pgm = PGMExplainer(model, explain_graph=True)

In [68]:
pgm_ne = pgm.get_explanation_graph(dataset[5].x, dataset[5].edge_index, forward_kwargs={'batch':None})

In [69]:
pgm_ne.node_imp

tensor([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 

In [ ]:
# def gnn_imp_nodes(node_idx, data):

#     node_exp = gnnexp.get_explanation_node(node_idx = node_idx, x = data.x, edge_index = data.edge_index)

#     imp_nodes = []

#     for k in node_exp.node_reference.keys():

#         if node_exp.node_imp[node_exp.node_reference[k]].item() == 1:

#             imp_nodes.append(k)

#     return imp_nodes

In [ ]:
# imp_nodes_ig = {}
# imp_nodes_gnn = {}
# imp_nodes_pge = {}
# imp_nodes_pgm = {}
# imp_nodes_cam = {}

# for node_idx in tqdm((data.test_mask == True).nonzero()):

#     if out[node_idx].argmax() != data.y[node_idx]:
#         continue

#     imp_nodes_ig[node_idx] = ig_imp_nodes(node_idx)
#     imp_nodes_gnn[node_idx] = gnn_imp_nodes(node_idx)
#     imp_nodes_pge[node_idx] = pge_imp_nodes(node_idx)
#     imp_nodes_pgm[node_idx] = pgm_imp_nodes(node_idx.item())
#     imp_nodes_cam[node_idx] = cam_imp_nodes(node_idx)